/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 industrial_robot.glb
Author: jacuo777 (https://sketchfab.com/jacuo777)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/industrial-robot-e5e6703e7788417e9761eb4dc516de5a
Title: Industrial Robot
*/

import { useGLTF } from "@react-three/drei";
import { useSpring, a } from "@react-spring/three";

export function IndustrialRobot({
  baseClicked,
  setBaseClicked,
  cilindroBaseClicked,
  setCilindroBaseClicked,
  cilindroPecaPrincClicked,
  setCilindroPecaPrincClicked,
  pecaRetaBracoClicked,
  setPecaRetaBracoClicked,
  ganchoBracoClicked,
  setGanchoBracoClicked,
  visibledAll,
  setVisibledAll,
  showPecas,
  setShowPecas,
  baseMeioClicked,
  setBaseMeioClicked,
}) {
  const { nodes, materials } = useGLTF("/industrial_robot.glb");

  const baseSpring = useSpring({
    position: showPecas ? [0, -19.6, 0] : [0, -6.6, 0],
    scale: baseClicked || !visibledAll ? 100 : 0,
  });

  const cilindroBaseSpring = useSpring({
    position: showPecas ? [-0.11, 0.1, 0.24] : [-0.11, 0.1, 0.14],
    scale: cilindroBaseClicked || !visibledAll ? 1 : 0,
  });

  const cilindroPecaPrincSpring = useSpring({
    position: showPecas ? [-0.15, -0.17, 0.24] : [0.02, -0.17, 0.24],
    scale: cilindroPecaPrincClicked || !visibledAll ? 1 : 0,
  });

  const pecaRetaBracoSpring = useSpring({
    position: showPecas ? [-5.91, 66.94, -31.83] : [5.91, 66.94, -31.83],
    scale: pecaRetaBracoClicked || !visibledAll ? 100 : 0,
  });

  const ganchoBracoSpring = useSpring({
    position: showPecas ? [-14.11, 75.34, 56.28] : [-3.11, 75.34, 46.28],
    scale: ganchoBracoClicked || !visibledAll ? 100 : 0,
  });

  const baseMeioASpring = useSpring({
    scale: baseMeioClicked || !visibledAll ? 1 : 0,
  });

  const baseMeioBSpring = useSpring({
    scale: baseMeioClicked || !visibledAll ? 100 : 0,
  });

  return (
    <group dispose={null}>
      <group scale={0.5}>
        <a.group
          position={baseSpring.position}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={baseSpring.scale}
          onClick={() => {
            setBaseClicked(true);
          }}
        >
          <mesh
            geometry={nodes.foundation_low_base_0.geometry}
            material={materials.base}
          />
          <mesh
            geometry={nodes.screw_low_base_0.geometry}
            material={materials.base}
            position={[0, 0, 0.07]}
          />
          <mesh
            geometry={nodes.screw2_low_base_0.geometry}
            material={materials.base}
            position={[0, 0, 0.16]}
          />
        </a.group>
        <group
          position={[0.33, 12.67, 0.33]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        >
          {/* cilindro da base  */}
          <a.group
            position={cilindroBaseSpring.position}
            scale={cilindroBaseSpring.scale}
            onClick={() => {
              setCilindroBaseClicked(true);
            }}
          >
            <mesh
              geometry={nodes.engine2_low_Engine_0.geometry}
              material={materials.Engine}
            />
            <mesh
              geometry={nodes.Cylinder004_Engine_0.geometry}
              material={materials.Engine}
            />
          </a.group>
          {/* cilindro peça principal*/}
          <a.group
            position={cilindroPecaPrincSpring.position}
            rotation={[-Math.PI / 2, -Math.PI / 2, 0]}
            scale={cilindroPecaPrincSpring.scale}
            onClick={() => {
              setCilindroPecaPrincClicked(true);
            }}
          >
            <mesh
              geometry={nodes.engine_low_Engine_0.geometry}
              material={materials.Engine}
            />
            <mesh
              geometry={nodes.Cylinder005_Engine_0.geometry}
              material={materials.Engine}
            />
          </a.group>
          <a.group
            scale={baseMeioASpring.scale}
            onClick={() => {
              setBaseMeioClicked(true);
            }}
          >
            <mesh
              geometry={nodes.Base_low_arm_0.geometry}
              material={materials.material}
            />
            <mesh
              geometry={nodes.BigCyl_low_arm_0.geometry}
              material={materials.material}
              position={[0.13, 0.16, 0.25]}
              rotation={[Math.PI / 6, 0, 0]}
            />
            <mesh
              geometry={nodes.decal_low_arm_0.geometry}
              material={materials.material}
              position={[0.22, -0.07, 0.12]}
            />
            <mesh
              geometry={nodes.decal3_low_arm_0.geometry}
              material={materials.material}
              position={[0.02, -0.01, 0.13]}
            />
            <mesh
              geometry={nodes.decal2_low_arm_0.geometry}
              material={materials.material}
              position={[0.22, 0.16, 0.25]}
            />
            <mesh
              geometry={nodes.wire2_low_arm_0.geometry}
              material={materials.material}
              position={[-0.08, -0.07, 0.14]}
              rotation={[0, 0, -1.22]}
            />
            <mesh
              geometry={nodes.prop_low_arm_0.geometry}
              material={materials.material}
              position={[0.01, 0.09, 0.13]}
            />
            <mesh
              geometry={nodes.wire_low_arm_0.geometry}
              material={materials.material}
              position={[-0.03, -0.08, 0.16]}
              rotation={[0, 0, -1.22]}
            />
            <mesh
              geometry={nodes.wire3_low_arm_0.geometry}
              material={materials.material}
              position={[-0.1, -0.05, 0.15]}
              rotation={[0, 0, -1.22]}
            />
          </a.group>
        </group>
        <a.group
          position={[14.47, 36.9, 17.46]}
          rotation={[-0.97, 0, 0]}
          scale={baseMeioBSpring.scale}
          onClick={() => {
            setBaseMeioClicked(true);
          }}
        >
          <mesh
            geometry={nodes.arm_low_arm_0.geometry}
            material={materials.material}
          />
          <mesh
            geometry={nodes.decal4_low_arm_0.geometry}
            material={materials.material}
            position={[0.01, 0.29, 0.02]}
          />
          <mesh
            geometry={nodes.BigWire_low_arm_0.geometry}
            material={materials.material}
            position={[0.05, -0.05, -0.11]}
            rotation={[-0.6, 0, -1.22]}
          />
          <mesh
            geometry={nodes.screw3_low_arm_0.geometry}
            material={materials.material}
            rotation={[-0.6, -Math.PI / 2, 0]}
          />
          <mesh
            geometry={nodes.screw4_low_arm_0.geometry}
            material={materials.material}
            position={[0, 0.58, -0.03]}
            rotation={[-0.6, -Math.PI / 2, 0]}
          />
        </a.group>
        {/* parte reta de cima do braço*/}
        <a.group
          position={pecaRetaBracoSpring.position}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={pecaRetaBracoSpring.scale}
          onClick={() => {
            setPecaRetaBracoClicked(true);
          }}
        >
          <mesh
            geometry={nodes.arm2_low_arm_0.geometry}
            material={materials.material}
          />
          <mesh
            geometry={nodes.screw5_low_arm_0.geometry}
            material={materials.material}
            position={[-0.09, -0.16, 0.08]}
            rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
          />
          <mesh
            geometry={nodes.wire4_low_arm_0.geometry}
            material={materials.material}
            position={[-0.15, -0.02, 0.07]}
            rotation={[0, 0, -1.22]}
          />
          <mesh
            geometry={nodes.wire5_low_arm_0.geometry}
            material={materials.material}
            position={[-0.15, -0.02, 0.05]}
            rotation={[0, 0, -1.22]}
          />
          <mesh
            geometry={nodes.wire6_low_arm_0.geometry}
            material={materials.material}
            position={[-0.16, -0.03, -0.01]}
            rotation={[0, 0, -1.22]}
          />
          <mesh
            geometry={nodes.wire7_low_arm_0.geometry}
            material={materials.material}
            position={[-0.15, -0.03, -0.02]}
            rotation={[0, 0, -1.22]}
          />
          <mesh
            geometry={nodes.screw6_low_arm_0.geometry}
            material={materials.material}
            position={[-0.09, -0.7, 0.08]}
            rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
          />
          <mesh
            geometry={nodes.wire8_low_arm_0.geometry}
            material={materials.material}
            position={[-0.03, -0.12, 0.06]}
            rotation={[0, 0, -1.22]}
          />
          <mesh
            geometry={nodes.electricbox_low_arm_0.geometry}
            material={materials.material}
            position={[-0.05, 0.01, 0.13]}
          />
          <mesh
            geometry={nodes.engine5_low_Engine_0.geometry}
            material={materials.Engine}
            position={[-0.06, 0, 0]}
            rotation={[-Math.PI / 2, -Math.PI / 2, 0]}
            scale={0.69}
          />
          <mesh
            geometry={nodes.engine4_low_Engine_0.geometry}
            material={materials.Engine}
            position={[-0.13, -0.09, 0.06]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={0.6}
          />
          <mesh
            geometry={nodes.engine3_low_Engine_0.geometry}
            material={materials.Engine}
            position={[-0.13, -0.09, 0.12]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={0.6}
          />
        </a.group>
        <a.group
          position={ganchoBracoSpring.position}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={ganchoBracoSpring.scale}
          onClick={() => {
            setGanchoBracoClicked(true);
          }}
        >
          <mesh
            geometry={nodes.ToolRotation_low_tool_0.geometry}
            material={materials.tool}
          />
          <mesh
            geometry={nodes.Tool_low_tool_0.geometry}
            material={materials.tool}
          />
        </a.group>
      </group>
    </group>
  );
}

useGLTF.preload("/industrial_robot.glb");
