/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 parafuso.glb
Author: 3D Scan (https://sketchfab.com/3DSCAN-2020)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/parafuso-screw-7c122638fdc6420490cafa94499bfe17
Title: PARAFUSO - SCREW
*/

import React, { useRef, useState } from "react";
import { useGLTF, Text } from "@react-three/drei";
import { useFrame, Canvas } from "@react-three/fiber";

const TextObj = ({ isClicked, X, Y, Z, text }) => {
  return (
    <Text
      scale={[20, 20, 20]}
      color="white" // default
      anchorX="center" // default
      anchorY="middle" // default
      position={[X, Y, Z]}
      visible={!isClicked}
    >
      {text}
    </Text>
  );
};

export function Parafuso(props) {
  const { nodes, materials } = useGLTF("/parafuso.glb");
  const [isClicked, setIsClicked] = useState(false);
  const mesh = useRef();
  useFrame(({ clock }) =>
    !isClicked
      ? (mesh.current.rotation.z = clock.getElapsedTime())
      : mesh.current.rotation.z
  );
  return (
    <group {...props} dispose={null} scale={0.1}>
      <mesh>
        <TextObj
          X={15}
          Y={20}
          Z={0}
          isClicked={isClicked}
          text={"Parafuso XYZ"}
        />
        <TextObj
          X={16.2}
          Y={15}
          Z={0}
          isClicked={isClicked}
          text={"Tamanho: 10cm"}
        />
        <TextObj
          X={16.6}
          Y={10}
          Z={0}
          isClicked={isClicked}
          text={"Em estoque: SIM"}
        />
      </mesh>
      <mesh
        ref={mesh}
        geometry={nodes.Object_2.geometry}
        material={materials.PARAFUSO_material}
        rotation={[-Math.PI / -2, 0, 0]}
        position={isClicked ? [0, -25, 0] : [0, 25, 0]}
        onClick={() => {
          isClicked ? setIsClicked(false) : setIsClicked(true);
        }}
      >
        <meshPhysicalMaterial
          color="#aaa"
          roughness={0.2}
          metalness={0.9}
          reflectivity={0.5}
          iridescense={0.3}
          iridescenseIOR={1}
          iridescenseThicknessRange={[100, 1000]}
        />
      </mesh>
    </group>
  );
}

useGLTF.preload("/parafuso.glb");
